{% set name = "libertem-live" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libertem-live-{{ version }}.tar.gz
  sha256: 27ff8de94b1ea34ee0f2f0b8ef13203d903b52b54946add72c39ab8984e5fe39

build:
  skip: True  # [py<37]
  entry_points:
    - libertem-live-mib-sim=libertem_live.detectors.merlin.sim:main
    - libertem-live-dectris-sim=libertem_live.detectors.dectris.sim:main
    - libertem-live-asi-tpx-sim=libertem_live.detectors.asi_tpx3.sim:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python
    - pip
  run:
    - python
    - libertem >=0.11.0
    - numpy
    - click
    - tqdm
    - numba
    - opentelemetry-api
    - sparseconverter
    - libertem-dectris
    - libertem-asi-tpx3

test:
  imports:
    - libertem_live
  commands:
    - pip check
    - libertem-live-mib-sim --help
    - libertem-live-dectris-sim --help
    - libertem-live-asi-tpx-sim --help
    - pytest tests
  source_files:
    - tests
    - conftest.py
    - pytest.ini
  requires:
    - pip
    - flask
    - pytest >=6
    - pytest-cov
    - pytest-asyncio >0.11
    - pytest-xdist
    - pytest-env
    - pytest-benchmark
    - pytest-timeout
    - aiohttp
    - websockets
    - ipykernel
    - nest-asyncio

about:
  home: https://libertem.github.io/LiberTEM-live
  summary: Live processing with LiberTEM
  license: GPL-3.0-or-later AND MIT
  license_file:
    - LICENSE
    - src/libertem_live/detectors/LICENSE
  description: |
    LiberTEM-live is an extension module for
    LiberTEM that allows live data processing.

extra:
  recipe-maintainers:
    - sk1p
    - uellue
    - matbryan52
